# Generated by Django 5.1.1 on 2024-09-21 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
