# Generated by Django 5.1.1 on 2024-09-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_alter_movie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
